### ISSUE TITLE
Configure styles framework

### ISSUE THREAD

**Issue by nathanstruhs** [osu-cascades/beaver-dam-analogues#1]

**Comment by ybakos** [comment]
@nathanstruhs FWIW, the `bootstrap` gem is the way to go, it provides bootstrap v4.

It's worth it to read into flexbox, which is a collection of CSS3 style/layout declarations. BS4 uses these behind the scenes.

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox
