### ISSUE TITLE
Heroku --remote staging does not recognize type "st_point"

### ISSUE THREAD

**Issue by nathanstruhs** [osu-cascades/beaver-dam-analogues#22]
Error `PG::UndefinedObject: ERROR:  type "st_point" does not exist
LINE 1: ALTER TABLE "projects" ADD "lonlat" st_point`

I have: 
- heroku run rake db:gis:setup --remote staging
- configured buildpacks
- setup database.yml with `adapter: postgis`

**Comment by ybakos** [comment]
Sounds like you have to manually enable the extension. Open up a db session using the db url and:

`CREATE EXTENSION postgis;`

**Comment by nathanstruhs** [comment]
![screen shot 2018-02-09 at 9 27 21 am](https://user-images.githubusercontent.com/13897382/36042240-0b89d6e0-0d80-11e8-95b8-02c6190897b6.png)
https://devcenter.heroku.com/articles/heroku-postgres-extensions-postgis-full-text-search#postgis

**Comment by nathanstruhs** [comment]
Needed `url: <%= ENV.fetch("DATABASE_URL", "").gsub(/postgres/, 'postgis') %>` in config/database.yml
