### ISSUE TITLE
DB schema: Add not null constraints, fk indices

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/beaver-dam-analogues#26]
If you take a look at the migrations, none of the attributes have `null: false` and the `author_id` doesn't have the `foreign_key: true` options. As a result, the db schema will allow null values in fields that should not be optional; and it won't create the default fk constraints or index on the foreign key.

Let's get the schema up to snuff before adding any more tables.

**Comment by nathanstruhs** [comment]
TODO: update all lonlat records to non null values before adding null constraint (dev, staging, production)
