### ISSUE TITLE
Project location: allow specifying degrees/minutes/seconds

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/beaver-dam-analogues#40]
Regardless of how we store the lonlat, let's let the user enter in either decimal or in (degreee, minute, second) values. The slickest UI would enable "switching" between both.

**Comment by ybakos** [comment]
What do you think about this, @webernick79 ?

**Comment by webernick79** [comment]
Again, unless it's really simple, don't worry about degree minute seconds. Most people function either in decimal degrees or UTM. However, I think it's fine to just stick with Decimal Degrees
