### ISSUE TITLE
Latitude and Longitude labels: Specify 'decimal degrees'

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/beaver-dam-analogues#41]
Let's append "decimal degrees" as the units for the existing lat/lon labels.

Per Matt Orr via email, 3/3/18.
"
For "latitude/longitude" you may end up needing two boxes for both decimal degrees and degrees/minutes/seconds. I put it in using degrees/minutes/seconds and got a message saying it had to be a number. At a minimum it should say "latitude (decimal degrees)" and "longitude (decimal degrees)" The only problem with having it only that way is that some people who aren't tech savvy will have a reading in degrees/minutes/seconds and not know how to convert. You could also put a link for converting: https://www.latlong.net/degrees-minutes-seconds-to-decimal-degrees
"

**Comment by ybakos** [comment]
What do you think about this, @webernick79 ?

**Comment by webernick79** [comment]
I wouldn't worry about DEGREES MIN. SEC. Lets just stick with Decimal Degrees. Again, user guidance is key, and would be good to offer a link to sites that allows conversion from Deg. Min. Sec. and UTM
