### ISSUE TITLE
Project Narrative: Guide user about expected content

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/beaver-dam-analogues#42]
Per Matt Orr via email, 3/3/18.

Under "Narrative" perhaps add a little guidance on what you are looking for. We can talk about that if you like.

**Comment by ybakos** [comment]
What do you think about this, @webernick79 ?

**Comment by webernick79** [comment]
Yes, we can give an example narrative and some guidance. I feel like a lot of the attributes need a bit of info to guide user. Let's discuss the best way to provide this?

**Comment by nathanstruhs** [comment]
@webernick79 For additional guidance, I was thinking a question mark button next to the field that would pull up a dialog could be useful. Something like: 
![image](https://user-images.githubusercontent.com/13897382/36948408-41a34506-1f8f-11e8-9b28-f1beb401ea64.png)

**Comment by webernick79** [comment]
Yup, that's perfect, I can help supply text for this stuff
