### ISSUE TITLE
Project "Area" too vague or needs refined name?

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/beaver-dam-analogues#43]
Per Matt Orr via email, 3/3/18.

I don't know about "Area" (meters). Maybe something like "estimated stream length of project" would be better.

**Comment by ybakos** [comment]
What do you think about this, @webernick79 ?

**Comment by webernick79** [comment]
Yes - "Treatment Length" would probably me most appropriate. I would say meters (m) is most appropriate measure.
