### ISSUE TITLE
Project 'maintenance' is vague?

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/beaver-dam-analogues#44]
Per Matt Orr via email, 3/3/18.

Or at least be more specific, like "Is your project being actively maintained?"

**Comment by ybakos** [comment]
What do you think about this, @webernick79 ?

**Comment by webernick79** [comment]
This is good - Actually, people keep getting concerned about the word "Maintenance". We may want to use "Adaptive Management", and we may need to somewhere define that this can include things like enhancements and/or repairs to a structure
